export const ADD_QUESTION = 'ADD_QUESTION';
export const ACTIVE_QUESTION = 'ACTIVE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const UPDATE_SURVEY_HEADER = 'UPDATE_SURVEY_HEADER';
export const SWITCH_TAB = 'SWITCH_TAB';